stages:
  run-api:
    cmd: uvicorn main:app --reload
    deps:
    - ./data/adult.data
    - ./data/adult.test
    outs:
    - ./model/income_classifier.joblib
    - ./data/training_clean.csv
    - ./data/training_hotencoding.csv
    - ./data/testing_clean.csv
    - ./data/testing_hotencoding.csv
    - ./data/training_pred.csv
    - ./data/testing_pred.csv

