stages:
  run-api:
    cmd: uvicorn app.main:app --reload
    deps:
    - ./app/data/adult.data
    - ./app/data/adult.test
    outs:
    - ./app/model/income_classifier.joblib
    - ./app/data/training_clean.csv
    - ./app/data/training_hotencoding.csv
    - ./app/data/testing_clean.csv
    - ./app/data/testing_hotencoding.csv
    - ./app/data/training_pred.csv
    - ./app/data/testing_pred.csv

